spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?characterEncoding=utf8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ${DB_PASSWORD}
  batch:
    initialize-schema: never