spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  batch:
    job:
      names: ${job.name:NONE}
    initialize-schema: always
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?characterEncoding=utf8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ${DB_PASSWORD}
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: localhost
stock:
  api:
    host: http://asp1.krx.co.kr/servlet/krx.asp.XMLSise?code=

